settings:
  title: 'Nodes Checker'
  url: 'https://nodes.licit.dev' # used for Slack & Discord messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
#   - id: workers-cloudflare-com # unique identifier
#     name: workers.cloudflare.com
#     description: 'You write code. They handle the rest.' # default=empty
#     url: 'https://workers.cloudflare.com/' # URL to fetch
#     method: GET # default=GET
#     expectStatus: 200 # operational status, default=200
#     followRedirect: false # should fetch follow redirects, default=false
#     linkable: false # allows the title to be a link, default=true

#   - id: www-cloudflare-com
#     name: www.cloudflare.com
#     description: 'Built for anything connected to the Internet.'
#     url: 'https://www.cloudflare.com'
#     method: GET
#     expectStatus: 200
#     linkable: true # allows the title to be a link, default=true

#   - id: blog-cloudflare-com
#     name: The Cloudflare Blog
#     url: 'https://blog.cloudflare.com/'
#     method: GET
#     expectStatus: 200

  - id: gcc3
    name: gcc3
    url: 'https://gcc3.licit.dev/'
    linkable: false
    
  - id: gcs1
    name: gcs1
    url: 'https://gcs1.licit.dev/'
    linkable: false
    
  - id: rnc1
    name: rnc1
    url: 'https://rnc1.licit.dev/'
    linkable: false
